// ==============================================================================
// nia mobility - Realistic Seed Dataset (Kenyan Mobility Ecosystem)
// Developed by Denory Codespace
// ==============================================================================

import {
  User,
  Profile,
  DriverProfile,
  PartnerProfile,
  Vehicle,
  VehicleListing,
  Application,
  Agreement,
  Conversation,
  Message,
  Review,
  VerificationDocument,
  NotificationItem,
} from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: "usr-admin-01",
    email: "admin@niamobility.co.ke",
    phone: "+254711000111",
    role: "ADMIN",
    isActive: true,
    isVerified: true,
    createdAt: "2026-01-01T08:00:00Z",
    updatedAt: "2026-01-01T08:00:00Z",
  },
  {
    id: "usr-partner-01",
    email: "kamau.fleet@gmail.com",
    phone: "+254722334455",
    role: "PARTNER",
    isActive: true,
    isVerified: true,
    createdAt: "2026-01-10T09:30:00Z",
    updatedAt: "2026-01-10T09:30:00Z",
  },
  {
    id: "usr-partner-02",
    email: "beatrice.mobility@gmail.com",
    phone: "+254733445566",
    role: "PARTNER",
    isActive: true,
    isVerified: true,
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-01-15T11:00:00Z",
  },
  {
    id: "usr-driver-01",
    email: "samuel.mwangi.driver@gmail.com",
    phone: "+254712345678",
    role: "DRIVER",
    isActive: true,
    isVerified: true,
    createdAt: "2026-01-20T14:15:00Z",
    updatedAt: "2026-01-20T14:15:00Z",
  },
  {
    id: "usr-driver-02",
    email: "brian.ochieng.kenya@gmail.com",
    phone: "+254798765432",
    role: "DRIVER",
    isActive: true,
    isVerified: true,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "usr-driver-03",
    email: "kevin.mutua.rides@gmail.com",
    phone: "+254745123987",
    role: "DRIVER",
    isActive: true,
    isVerified: false,
    createdAt: "2026-02-10T16:45:00Z",
    updatedAt: "2026-02-10T16:45:00Z",
  },
];

export const MOCK_PROFILES: Profile[] = [
  {
    id: "prof-admin-01",
    userId: "usr-admin-01",
    fullName: "Denzel (Denory Lead)",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    locationCounty: "Nairobi",
    locationSubcounty: "Westlands",
    bio: "Platform Administrator at nia mobility by Denory Codespace.",
    createdAt: "2026-01-01T08:00:00Z",
    updatedAt: "2026-01-01T08:00:00Z",
  },
  {
    id: "prof-partner-01",
    userId: "usr-partner-01",
    fullName: "David Kamau (Apex Fleets)",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    locationCounty: "Nairobi",
    locationSubcounty: "Kasarani / Thika Road",
    bio: "Managing a fleet of well-maintained Toyota Fielders and Axios with fair daily targets and prompt maintenance support.",
    createdAt: "2026-01-10T09:30:00Z",
    updatedAt: "2026-01-10T09:30:00Z",
  },
  {
    id: "prof-partner-02",
    userId: "usr-partner-02",
    fullName: "Beatrice Nduta",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    locationCounty: "Nairobi",
    locationSubcounty: "Kilimani",
    bio: "Individual vehicle owner seeking a disciplined, verified driver for a Nissan Note on Uber & Little.",
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-01-15T11:00:00Z",
  },
  {
    id: "prof-driver-01",
    userId: "usr-driver-01",
    fullName: "Samuel Mwangi",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    locationCounty: "Nairobi",
    locationSubcounty: "Roysambu",
    bio: "Professional driver with 5+ years experience on Uber and Bolt. Clean driving record, PSV badge, and excellent customer ratings.",
    createdAt: "2026-01-20T14:15:00Z",
    updatedAt: "2026-01-20T14:15:00Z",
  },
  {
    id: "prof-driver-02",
    userId: "usr-driver-02",
    fullName: "Brian Ochieng",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    locationCounty: "Nairobi",
    locationSubcounty: "Embakasi",
    bio: "Experienced driver specializing in Airport and CBD routes. Punctual, non-smoker, reliable daily remittance.",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
];

export const MOCK_DRIVER_PROFILES: DriverProfile[] = [
  {
    id: "drv-01",
    userId: "usr-driver-01",
    drivingExperienceYears: 5,
    preferredOperatingAreas: ["Westlands", "Kasarani", "CBD / Starehe", "Roysambu"],
    preferredPlatforms: ["Uber", "Bolt", "Little"],
    preferredVehicleTypes: ["SEDAN", "HATCHBACK"],
    preferredArrangementTypes: ["DAILY_TARGET", "WEEKLY_TARGET"],
    maxDailyTargetKes: 3000,
    availableFrom: "2026-02-01T00:00:00Z",
    isAvailable: true,
    ratingAvg: 4.9,
    ratingCount: 28,
    completedEngagementsCount: 4,
    identityVerified: true,
    licenseVerified: true,
    createdAt: "2026-01-20T14:15:00Z",
    updatedAt: "2026-01-20T14:15:00Z",
  },
  {
    id: "drv-02",
    userId: "usr-driver-02",
    drivingExperienceYears: 3,
    preferredOperatingAreas: ["Embakasi", "CBD / Starehe", "South B / South C"],
    preferredPlatforms: ["Uber", "Faras", "Yango"],
    preferredVehicleTypes: ["SEDAN"],
    preferredArrangementTypes: ["DAILY_TARGET"],
    maxDailyTargetKes: 2800,
    availableFrom: "2026-02-15T00:00:00Z",
    isAvailable: true,
    ratingAvg: 4.8,
    ratingCount: 14,
    completedEngagementsCount: 2,
    identityVerified: true,
    licenseVerified: true,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
];

export const MOCK_PARTNER_PROFILES: PartnerProfile[] = [
  {
    id: "prt-01",
    userId: "usr-partner-01",
    partnerType: "FLEET_OPERATOR",
    companyName: "Apex Fleets Kenya",
    ratingAvg: 4.9,
    ratingCount: 32,
    totalVehiclesCount: 4,
    activeAgreementsCount: 2,
    identityVerified: true,
    businessVerified: true,
    createdAt: "2026-01-10T09:30:00Z",
    updatedAt: "2026-01-10T09:30:00Z",
  },
  {
    id: "prt-02",
    userId: "usr-partner-02",
    partnerType: "INDIVIDUAL",
    companyName: "Beatrice Ventures",
    ratingAvg: 5.0,
    ratingCount: 8,
    totalVehiclesCount: 1,
    activeAgreementsCount: 0,
    identityVerified: true,
    businessVerified: false,
    createdAt: "2026-01-15T11:00:00Z",
    updatedAt: "2026-01-15T11:00:00Z",
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "veh-01",
    partnerId: "prt-01",
    make: "Toyota",
    model: "Fielder (1.5L WxB)",
    year: 2018,
    registrationNumber: "KDG 482B",
    vehicleType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    seatingCapacity: 4,
    color: "Pearl White",
    mileageKm: 98400,
    primaryCounty: "Nairobi",
    primarySubcounty: "Kasarani",
    supportedPlatforms: ["Uber", "Bolt", "Little", "Faras"],
    photos: [
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80"
    ],
    verificationStatus: "VERIFIED",
    availabilityStatus: "AVAILABLE",
    createdAt: "2026-01-12T10:00:00Z",
    updatedAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "veh-02",
    partnerId: "prt-01",
    make: "Toyota",
    model: "Axio",
    year: 2017,
    registrationNumber: "KDF 914Z",
    vehicleType: "SEDAN",
    transmission: "AUTOMATIC",
    fuelType: "HYBRID",
    seatingCapacity: 4,
    color: "Silver Metallic",
    mileageKm: 112000,
    primaryCounty: "Nairobi",
    primarySubcounty: "Westlands",
    supportedPlatforms: ["Uber", "Bolt", "Little"],
    photos: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&auto=format&fit=crop&q=80"
    ],
    verificationStatus: "VERIFIED",
    availabilityStatus: "AVAILABLE",
    createdAt: "2026-01-14T11:30:00Z",
    updatedAt: "2026-01-14T11:30:00Z",
  },
  {
    id: "veh-03",
    partnerId: "prt-02",
    make: "Nissan",
    model: "Note (e-Power)",
    year: 2019,
    registrationNumber: "KDD 312M",
    vehicleType: "HATCHBACK",
    transmission: "AUTOMATIC",
    fuelType: "HYBRID",
    seatingCapacity: 4,
    color: "Midnight Blue",
    mileageKm: 76000,
    primaryCounty: "Nairobi",
    primarySubcounty: "Kilimani / Kileleshwa",
    supportedPlatforms: ["Uber", "Bolt", "Little", "Yango"],
    photos: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80"
    ],
    verificationStatus: "VERIFIED",
    availabilityStatus: "AVAILABLE",
    createdAt: "2026-01-18T09:00:00Z",
    updatedAt: "2026-01-18T09:00:00Z",
  },
  {
    id: "veh-04",
    partnerId: "prt-01",
    make: "Mazda",
    model: "Demio Skyactiv",
    year: 2016,
    registrationNumber: "KDC 602A",
    vehicleType: "HATCHBACK",
    transmission: "AUTOMATIC",
    fuelType: "PETROL",
    seatingCapacity: 4,
    color: "Ruby Red",
    mileageKm: 125000,
    primaryCounty: "Nairobi",
    primarySubcounty: "Embakasi",
    supportedPlatforms: ["Bolt", "Faras", "Uber"],
    photos: [
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=80"
    ],
    verificationStatus: "VERIFIED",
    availabilityStatus: "AVAILABLE",
    createdAt: "2026-01-22T14:00:00Z",
    updatedAt: "2026-01-22T14:00:00Z",
  }
];

export const MOCK_LISTINGS: VehicleListing[] = [
  {
    id: "lst-01",
    vehicleId: "veh-01",
    partnerId: "prt-01",
    title: "Toyota Fielder 2018 - Clean & Ready for Uber/Bolt in Nairobi",
    description: "Well maintained Toyota Fielder with comprehensive commercial insurance, active tracker, and full service history. Looking for a disciplined driver with 3+ years experience. Service and major repairs covered by owner.",
    county: "Nairobi",
    subcounty: "Kasarani",
    arrangementType: "DAILY_TARGET",
    targetAmountKes: 2800,
    depositAmountKes: 15000,
    paymentFrequency: "DAILY",
    fuelResponsibility: "DRIVER",
    maintenanceResponsibility: "PARTNER",
    insuranceResponsibility: "PARTNER",
    preferredPlatforms: ["Uber", "Bolt", "Little"],
    driverMinExperienceYears: 3,
    driverRequirementsSummary: "Must have valid DL, clean NTSA record, PSV badge, and verified residence in Nairobi.",
    availableFrom: "2026-02-01T00:00:00Z",
    status: "PUBLISHED",
    viewCount: 142,
    applicationsCount: 4,
    publishedAt: "2026-01-25T10:00:00Z",
    createdAt: "2026-01-25T10:00:00Z",
    updatedAt: "2026-01-25T10:00:00Z",
    vehicle: MOCK_VEHICLES[0],
    partner: {
      id: "prt-01",
      fullName: "David Kamau (Apex Fleets)",
      ratingAvg: 4.9,
      ratingCount: 32,
      isVerified: true,
    }
  },
  {
    id: "lst-02",
    vehicleId: "veh-02",
    partnerId: "prt-01",
    title: "Toyota Axio Hybrid 2017 - Fuel Efficient (Westlands & CBD)",
    description: "Hybrid efficiency giving up to 22 km/l. Perfect for high-volume CBD & Westlands operations. Weekly settlement with regular bi-weekly mechanical checkups covered by fleet.",
    county: "Nairobi",
    subcounty: "Westlands",
    arrangementType: "WEEKLY_TARGET",
    targetAmountKes: 18000, // KES 18,000 / week (approx 2,570/day)
    depositAmountKes: 20000,
    paymentFrequency: "WEEKLY",
    fuelResponsibility: "DRIVER",
    maintenanceResponsibility: "PARTNER",
    insuranceResponsibility: "PARTNER",
    preferredPlatforms: ["Uber", "Bolt", "Little"],
    driverMinExperienceYears: 2,
    driverRequirementsSummary: "Demonstrated experience with hybrid vehicles preferred.",
    availableFrom: "2026-02-05T00:00:00Z",
    status: "PUBLISHED",
    viewCount: 98,
    applicationsCount: 2,
    publishedAt: "2026-01-26T14:00:00Z",
    createdAt: "2026-01-26T14:00:00Z",
    updatedAt: "2026-01-26T14:00:00Z",
    vehicle: MOCK_VEHICLES[1],
    partner: {
      id: "prt-01",
      fullName: "David Kamau (Apex Fleets)",
      ratingAvg: 4.9,
      ratingCount: 32,
      isVerified: true,
    }
  },
  {
    id: "lst-03",
    vehicleId: "veh-03",
    partnerId: "prt-02",
    title: "Nissan Note e-Power 2019 - Excellent Condition (Kilimani)",
    description: "Modern, quiet, and highly economical Nissan Note e-Power. Daily target arrangement with flexible off-days. Comprehensive insurance and speed governor active.",
    county: "Nairobi",
    subcounty: "Kilimani / Kileleshwa",
    arrangementType: "DAILY_TARGET",
    targetAmountKes: 2600,
    depositAmountKes: 12000,
    paymentFrequency: "DAILY",
    fuelResponsibility: "DRIVER",
    maintenanceResponsibility: "PARTNER",
    insuranceResponsibility: "PARTNER",
    preferredPlatforms: ["Uber", "Bolt", "Little", "Yango"],
    driverMinExperienceYears: 2,
    driverRequirementsSummary: "Must provide 2 verifiable referee contacts and valid Certificate of Good Conduct.",
    availableFrom: "2026-02-10T00:00:00Z",
    status: "PUBLISHED",
    viewCount: 65,
    applicationsCount: 1,
    publishedAt: "2026-01-28T09:00:00Z",
    createdAt: "2026-01-28T09:00:00Z",
    updatedAt: "2026-01-28T09:00:00Z",
    vehicle: MOCK_VEHICLES[2],
    partner: {
      id: "prt-02",
      fullName: "Beatrice Nduta",
      ratingAvg: 5.0,
      ratingCount: 8,
      isVerified: true,
    }
  },
  {
    id: "lst-04",
    vehicleId: "veh-04",
    partnerId: "prt-01",
    title: "Mazda Demio 2016 - Affordable Daily Target (Embakasi)",
    description: "Compact, easy to navigate, low maintenance cost. Ideal for drivers targeting Eastlands and Airport corridor.",
    county: "Nairobi",
    subcounty: "Embakasi",
    arrangementType: "DAILY_TARGET",
    targetAmountKes: 2300,
    depositAmountKes: 10000,
    paymentFrequency: "DAILY",
    fuelResponsibility: "DRIVER",
    maintenanceResponsibility: "PARTNER",
    insuranceResponsibility: "PARTNER",
    preferredPlatforms: ["Bolt", "Faras", "Uber"],
    driverMinExperienceYears: 1,
    driverRequirementsSummary: "Friendly, courteous, and respectful of maintenance schedules.",
    availableFrom: "2026-02-01T00:00:00Z",
    status: "PUBLISHED",
    viewCount: 81,
    applicationsCount: 3,
    publishedAt: "2026-01-29T11:00:00Z",
    createdAt: "2026-01-29T11:00:00Z",
    updatedAt: "2026-01-29T11:00:00Z",
    vehicle: MOCK_VEHICLES[3],
    partner: {
      id: "prt-01",
      fullName: "David Kamau (Apex Fleets)",
      ratingAvg: 4.9,
      ratingCount: 32,
      isVerified: true,
    }
  }
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app-01",
    listingId: "lst-01",
    driverId: "drv-01",
    partnerId: "prt-01",
    status: "INTERVIEW",
    coverNote: "Hello Apex Fleets, I have 5 years driving on Uber & Bolt with a 4.9 rating. I reside in Roysambu near Kasarani and can maintain punctual daily targets via M-PESA.",
    matchScorePct: 94,
    statusReason: "Shortlisted after document review.",
    lastStatusChangedBy: "usr-partner-01",
    lastStatusChangedAt: "2026-01-27T16:00:00Z",
    createdAt: "2026-01-26T11:00:00Z",
    updatedAt: "2026-01-27T16:00:00Z",
    listing: MOCK_LISTINGS[0],
    driver: {
      id: "drv-01",
      fullName: "Samuel Mwangi",
      phone: "+254712345678",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      experienceYears: 5,
      ratingAvg: 4.9,
      isVerified: true,
      preferredPlatforms: ["Uber", "Bolt", "Little"],
      locationSubcounty: "Roysambu",
    },
    partner: {
      id: "prt-01",
      fullName: "David Kamau (Apex Fleets)",
      phone: "+254722334455",
    }
  },
  {
    id: "app-02",
    listingId: "lst-04",
    driverId: "drv-02",
    partnerId: "prt-01",
    status: "ACCEPTED",
    coverNote: "Hi David, I live in Embakasi and focus on Faras and Bolt around the airport. Ready with deposit.",
    matchScorePct: 91,
    statusReason: "Application accepted. Preparing formal agreement.",
    lastStatusChangedBy: "usr-partner-01",
    lastStatusChangedAt: "2026-01-30T10:00:00Z",
    createdAt: "2026-01-29T15:00:00Z",
    updatedAt: "2026-01-30T10:00:00Z",
    listing: MOCK_LISTINGS[3],
    driver: {
      id: "drv-02",
      fullName: "Brian Ochieng",
      phone: "+254798765432",
      avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
      experienceYears: 3,
      ratingAvg: 4.8,
      isVerified: true,
      preferredPlatforms: ["Uber", "Faras", "Yango"],
      locationSubcounty: "Embakasi",
    },
    partner: {
      id: "prt-01",
      fullName: "David Kamau (Apex Fleets)",
      phone: "+254722334455",
    }
  }
];

export const MOCK_AGREEMENTS: Agreement[] = [
  {
    id: "agr-01",
    agreementNumber: "NIA-AGR-2026-0042",
    applicationId: "app-02",
    listingId: "lst-04",
    driverId: "drv-02",
    partnerId: "prt-01",
    vehicleId: "veh-04",
    arrangementType: "DAILY_TARGET",
    targetAmountKes: 2300,
    depositAmountKes: 10000,
    paymentFrequency: "DAILY",
    fuelTerms: "Fuel cost borne 100% by driver. Tank handed over full and returned full.",
    maintenanceTerms: "Routine 5,000 km servicing and wear & tear covered by Apex Fleets. Driver responsible for reporting mechanical alerts promptly.",
    insuranceTerms: "Commercial PSV comprehensive insurance maintained and paid by Partner.",
    operatingArea: "Nairobi Metropolitan Area",
    startDate: "2026-02-01T00:00:00Z",
    endDate: "2026-08-01T00:00:00Z",
    termsAndConditions: "Standard nia mobility operating framework. Daily target remittance by 22:00 EAT via M-PESA. Vehicle tracking active.",
    status: "ACTIVE",
    partnerSignedAt: "2026-01-30T12:00:00Z",
    driverSignedAt: "2026-01-30T14:30:00Z",
    createdAt: "2026-01-30T11:00:00Z",
    updatedAt: "2026-01-30T14:30:00Z",
    vehicle: MOCK_VEHICLES[3],
    driverName: "Brian Ochieng",
    partnerName: "David Kamau (Apex Fleets)",
  }
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-01",
    driverId: "drv-01",
    partnerId: "prt-01",
    driverName: "Samuel Mwangi",
    partnerName: "David Kamau (Apex Fleets)",
    listingId: "lst-01",
    listingTitle: "Toyota Fielder 2018 - Clean & Ready for Uber/Bolt",
    lastMessage: "Sounds good Samuel, please bring your original DL to Westlands tomorrow at 10 AM for physical inspection.",
    lastMessageAt: "2026-01-27T17:15:00Z",
    unreadCount: 1,
    createdAt: "2026-01-27T16:05:00Z",
  }
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg-01",
    conversationId: "conv-01",
    senderId: "usr-partner-01",
    senderName: "David Kamau",
    senderRole: "PARTNER",
    content: "Habari Samuel, I saw your application. Your 5-year experience and 4.9 rating look impressive. Are you comfortable with the KES 2,800 daily target?",
    isRead: true,
    createdAt: "2026-01-27T16:10:00Z",
  },
  {
    id: "msg-02",
    conversationId: "conv-01",
    senderId: "usr-driver-01",
    senderName: "Samuel Mwangi",
    senderRole: "DRIVER",
    content: "Habari Mr. Kamau! Yes, absolutely. I operate mostly along Thika Road and Westlands where demand is solid, so KES 2,800 is very workable for me.",
    isRead: true,
    createdAt: "2026-01-27T16:40:00Z",
  },
  {
    id: "msg-03",
    conversationId: "conv-01",
    senderId: "usr-partner-01",
    senderName: "David Kamau",
    senderRole: "PARTNER",
    content: "Sounds good Samuel, please bring your original DL to Westlands tomorrow at 10 AM for physical inspection.",
    isRead: false,
    createdAt: "2026-01-27T17:15:00Z",
  }
];

export const MOCK_VERIFICATION_DOCS: VerificationDocument[] = [
  {
    id: "doc-01",
    userId: "usr-driver-01",
    documentType: "NATIONAL_ID",
    documentNumber: "32984112",
    fileName: "samuel_mwangi_national_id.pdf",
    fileUrl: "https://example.com/docs/id.pdf",
    status: "VERIFIED",
    verifiedAt: "2026-01-21T09:00:00Z",
    createdAt: "2026-01-20T14:30:00Z",
  },
  {
    id: "doc-02",
    userId: "usr-driver-01",
    documentType: "DRIVING_LICENSE",
    documentNumber: "DL-99482-KE",
    fileName: "samuel_mwangi_driving_license.pdf",
    fileUrl: "https://example.com/docs/dl.pdf",
    status: "VERIFIED",
    verifiedAt: "2026-01-21T09:15:00Z",
    createdAt: "2026-01-20T14:35:00Z",
  },
  {
    id: "doc-03",
    userId: "usr-driver-03",
    documentType: "DRIVING_LICENSE",
    documentNumber: "DL-11849-KE",
    fileName: "kevin_mutua_dl_scan.jpg",
    fileUrl: "https://example.com/docs/dl_kevin.jpg",
    status: "UNDER_REVIEW",
    createdAt: "2026-02-10T16:50:00Z",
  }
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-01",
    userId: "usr-driver-01",
    title: "Application Shortlisted! 🎉",
    message: "David Kamau shortlisted your application for Toyota Fielder 2018 (KDG 482B).",
    type: "APPLICATION",
    isRead: false,
    linkUrl: "/driver/applications",
    createdAt: "2026-01-27T16:00:00Z",
  },
  {
    id: "notif-02",
    userId: "usr-partner-01",
    title: "Agreement Signed! ✍️",
    message: "Brian Ochieng signed agreement NIA-AGR-2026-0042 for Mazda Demio (KDC 602A).",
    type: "AGREEMENT",
    isRead: true,
    linkUrl: "/partner/agreements",
    createdAt: "2026-01-30T14:30:00Z",
  }
];
